version: '3.1'

services:


    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9055:80
        volumes:
            - ./api:/var/www/html


    db:
        image: mariadb
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1